// <auto-generated />
namespace PhamDaiTruong_2011069041.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class khoitaocacbangchochucnangchungthucnguoidung : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(khoitaocacbangchochucnangchungthucnguoidung));
        
        string IMigrationMetadata.Id
        {
            get { return "202303172352324_khoi tao cac bang cho chuc nang chung thuc nguoi dung"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
